Algoritmo "ex08_metros_para_centimetros"
// Disciplina   : Lógica de Programação com Visualg
// Professor    : Jailson Costa dos Santos
// Descrição    : Converter metros para centímetros
// Autor(a)     : Beatriz Prates Dos Santos Morais
// Data atual   : 04/04/2026
Var
   // Seção de Declarações das variáveis
   metros, centimetros: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o valor em metros:\n")
   leia(metros)

   centimetros <- metros * 100

   escreva("O valor em centímetros é: ", centimetros)

Fimalgoritmo