Algoritmo "ex17_areacirculo"
// Disciplina   : Lógica de Programação com Visualg
// Professor    : Jailson Costa dos Santos
// Descrição    : Calcular a área de um círculo
// Autor(a)     : Beatriz Prates Dos Santos Morais
// Data atual   : 06/04/2026
Var
   // Seção de Declarações das variáveis
   raio, area: real


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite o raio do círculo: ")
   leia(raio)

   // Fórmula horizontalizada
   area <- 3.14 * raio^2 (raio)

   escreval("Área do círculo: ", area)


Fimalgoritmo