Algoritmo "ex23_positivo_negativo"
// Disciplina   : Lógica de Programação com Visualg
// Professor    : Jailson Costa dos Santos
// Descrição    : Verificar se valor é positivo ou negativo
// Autor(a)     : Beatriz Prates Dos Santos Morais
// Data atual   : 06/04/2026
Var
   // Seção de Declarações das variáveis
   valor: real


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite um valor: ")
   leia(valor)

   se valor >= 0 entao
      escreval("Positivo!")
   senao
      escreval("Negativo!")
   fimse


Fimalgoritmo