Algoritmo "ex_extra_a_produto_soma"
// Disciplina   : Lógica de Programação com Visualg
// Professor    : Jailson Costa dos Santos
// Descrição    : Calcular o produto de A com C e a soma de B com D
// Autor(a)     : Beatriz Prates Dos Santos Morais
// Data atual   : 06/04/2026
Var
   // Seção de Declarações das variáveis
   a, b, c, d, p, s: real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite o valor de A: ")
   Leia(a)
   Escreval("Digite o valor de B: ")
   Leia(b)
   Escreval("Digite o valor de C: ")
   Leia(c)
   Escreval("Digite o valor de D: ")
   Leia(d)
   p <- a * c
   s <- b + d
   Escreval("Produto de A com C: ", p)
   Escreval("Soma de B com D: ", s)

Fimalgoritmo