Algoritmo "ex_g_distributiva"
// Disciplina   : Lógica de Programação com Visualg
// Professor    : Jailson Costa dos Santos
// Descrição    : Somar e multiplicar combinacoes de quatro numeros
// Autor(a)     : Beatriz Prates Dos Santos Morais
// Data atual   : 06/04/2026
Var
   // Seção de Declarações das variáveis
   a, b, c, d: real


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite o valor de A: ")
   Leia(a)
   Escreval("Digite o valor de B: ")
   Leia(b)
   Escreval("Digite o valor de C: ")
   Leia(c)
   Escreval("Digite o valor de D: ")
   Leia(d)
   Escreval("A + B = ", a + b)
   Escreval("A * B = ", a * b)
   Escreval("A + C = ", a + c)
   Escreval("A * C = ", a * c)
   Escreval("A + D = ", a + d)
   Escreval("A * D = ", a * d)
   Escreval("B + C = ", b + c)
   Escreval("B * C = ", b * c)
   Escreval("B + D = ", b + d)
   Escreval("B * D = ", b * d)
   Escreval("C + D = ", c + d)
   Escreval("C * D = ", c * d)


Fimalgoritmo