Algoritmo "ex02_areaquadrado"
// Disciplina   : Lógica de Programação com Visualg
// Professor    : Jailson Costa dos Santos
// Descrição    : Calcular a área do quadrado
// Autor(a)     : Beatriz Prates Dos Santos Morais
// Data atual   : 06/04/2026
Var
   // Seção de Declarações das variáveis
   lado, area: real


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite o valor do lado do quadrado: ")
   leia(lado)

   // Fórmula horizontalizada
   area <- lado * lado

   escreval("Área do quadrado: ", area)



Fimalgoritmo