Algoritmo "ex03_perimetroquadrado"
// Disciplina   : Lógica de Programação com Visualg
// Professor    : Jailson Costa dos Santos
// Descrição    : Calcular o perímetro do quadrado
// Autor(a)     : Beatriz Prates Dos Santos Morais
// Data atual   : 06/04/2026
Var
   // Seção de Declarações das variáveis
   lado, perimetro: real


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite o valor do lado do quadrado: ")
   leia(lado)

   // Fórmula horizontalizada
   perimetro <- 4 * lado

   escreval("Perímetro do quadrado: ", perimetro)


Fimalgoritmo