Algoritmo "ex08_comprimentocircunferencia"
// Disciplina   : Lógica de Programação com Visualg
// Professor    : Jailson Costa dos Santos
// Descrição    : Calcular o comprimento da circunferência
// Autor(a)     : Beatriz Prates Dos Santos Morais
// Data atual   : 06/04/2026
Var
   // Seção de Declarações das variáveis
   raio, comprimento: real


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite o valor do raio: ")
   leia(raio)

   // Fórmula horizontalizada
   comprimento <- 2 * 3.14 * raio

   escreval("Comprimento da circunferência: ", comprimento)



Fimalgoritmo